name: Deploy Frontend to EC2

on:
  push:
    branches: [ "deploy" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
            sudo systemctl start docker
            sudo systemctl enable docker
            if [ ! -d "DevOps-InnovaTech" ]; then
              git clone https://github.com/${{ github.repository }} DevOps-InnovaTech
            fi
            cd DevOps-InnovaTech
            git pull origin deploy
            sudo docker compose up -d --build